config/routes.rb
Rails.application.routes.draw do
  resources :user_sessions
  get 'login' => 'user_sessions#new', as: :login
  get 'logout' => 'user_sessions#destroy', as: :logout

  post 'sms/receive', to: 'sms#receive'
  get 'help', to: 'page#help', as: :help

  resources :users do
    resources :questions do
      resources :answers, except: [:new, :edit, :update, :create]
    end
    resources :mobile_phones, except: [:index] do
      member do
        post :verify
        get  :reset
      end
    end
  end

  root to: 'dashboard#index', constraints: RouteConstraints::UserRequiredConstraint.new,
       as: :dashboard
  root to: 'page#welcome', constraints: RouteConstraints::NoUserRequiredConstraint.new,
       as: :landing
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers

  default_scope { order(created_at: :desc) }

  validates :body, presence: true, length: { in: 1..255 }
  validates :user_id, presence: true

  STOCK_QUESTIONS = ['Are you working?', 'Who are you with?', 'How do you feel?'].freeze
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /users/1/questions
  # GET /users/1/questions.json
  def index
    @questions = current_user.questions.all
  end

  # GET /users/1/questions/1
  # GET /users/1/questions/1.json
  def show
  end

  # GET /users/1/questions/new
  def new
    @question = Question.new
  end

  # GET /users/1/questions/1/edit
  def edit
  end

  # POST /users/1/questions
  # POST /users/1/questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html {
          redirect_to [current_user, @question],
                      notice: 'Question was successfully created.'
        }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1/questions/1
  # PATCH/PUT /users/1/questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html {
          redirect_to [current_user, @question],
                      notice: 'Question was successfully updated.'
        }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1/questions/1
  # DELETE /users/1/questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html {
        redirect_to user_questions_url(current_user),
                    notice: 'Question was successfully destroyed.'
      }
      format.json { head :no_content }
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def question_params
    params.require(:question).permit(:body, :askable).merge(user: current_user)
  end
end

app/views/questions/_form.html.haml
= form_for [current_user, @question] do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Show', [current_user, @question]
\|
= link_to 'Back', user_questions_path(current_user)

app/views/questions/index.html.haml
%h1 Your Questions

%table
  %thead
    %tr
      %th Question
      %th
      %th

  %tbody
    - @questions.each do |question|
      %tr
        %td= question.body
        %td= link_to 'Edit', edit_user_question_path(current_user, question)
        %td= link_to 'Destroy', [current_user, question], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Question', new_user_question_path(current_user)

app/views/questions/new.html.haml
%h1 New question

= render 'form'

= link_to 'Back', user_questions_path(current_user)

app/views/questions/show.html.haml
%p#notice= notice

%h2= @question.body
%hr

- if @question.answers.any?
  %ul
  - @question.answers.each do |answer|
    %li= answer.body
- else
  %p Looks like there are no answers yet for this question.