config/routes.rb
Rails.application.routes.draw do
  resources :user_sessions
  get 'login' => 'user_sessions#new', as: :login
  get 'logout' => 'user_sessions#destroy', as: :logout

  post 'sms/receive', to: 'sms#receive'
  get 'help', to: 'page#help', as: :help

  resources :users do
    resources :questions do
      resources :answers, except: [:new, :edit, :update, :create]
    end
    resources :mobile_phones, except: [:index] do
      member do
        post :verify
        get  :reset
      end
    end
  end

  root to: 'dashboard#index', constraints: RouteConstraints::UserRequiredConstraint.new,
       as: :dashboard
  root to: 'page#welcome', constraints: RouteConstraints::NoUserRequiredConstraint.new,
       as: :landing
end

app/models/mobile_phone.rb
class MobilePhone < ActiveRecord::Base
  belongs_to :user
  has_many :smses, class: SMS

  default_scope { order(created_at: :desc) }

  # TODO(chase): add uniqueness to validation: {scope: :user_id}
  validates :number, presence: true,
                     format: {with: /\A\+\d{11}\z/,
                              message: 'is invalid, please format like ' +
                                       '+18598675309'},
                     uniqueness: {scope: :user_id}

  before_create :set_random_auth_code
  after_update :reset_verification!, if: :verified_and_changed?
  after_save :send_auth_code, if: :unverified_and_new_auth_code?
  before_save :set_random_auth_code, if: :number_changed?

  def verified_and_changed?
    number_changed? && verified?
  end

  def reset_verification!
    update_attribute(:verified, false)
  end

  def self.generate_auth_code
    '%05d' % SecureRandom.random_number(99999)
  end

  def verified!
    update_attribute(:verified, true)
  end

  def unverified?
    !verified?
  end

  def disable!
    update_column(:disabled, true)
  end

  def enable!
    update_column(:disabled, false)
  end

  def enabled?
    !disabled?
  end

  private

  def set_random_auth_code
    self.auth_code = self.class.generate_auth_code
  end

  def send_auth_code
    body = "Inquisitor auth code: #{auth_code}"
    SMSWorker.perform_async(number, body)
  end

  def unverified_and_new_auth_code?
    unverified? && auth_code_changed?
  end
end

app/controllers/mobile_phones_controller.rb
class MobilePhonesController < ApplicationController
  before_action :set_mobile_phone, except: [:new, :create]

  # GET /mobile_phones/new
  def new
    @mobile_phone = MobilePhone.new
  end

  # POST /mobile_phones
  def create
    @mobile_phone = MobilePhone.new(mobile_phone_params)
    if @mobile_phone.save
      flash[:notice] = 'Saved! We will send you a code to ' +
                       'verify your number.'
      redirect_to user_mobile_phone_path(current_user, @mobile_phone)
    else
      flash[:warning] = 'Failed to save phone number.'
      render :new
    end
  end

  # GET /mobile_phones/1
  def show
  end

  # GET /mobile_phones/1/edit
  def edit
  end

  # PUT /mobile_phones/1
  def update
    if @mobile_phone.update(mobile_phone_params)
      flash[:notice] = 'Your phone has been updated.'
    else
      flash[:warning] = 'We could not update your phone.'
    end
    redirect_to user_mobile_phone_path(current_user, @mobile_phone)
  end

  # DELETE /mobile_phones/1
  def destroy
  end

  # POST /mobile_phones/1/verify
  def verify
    if @mobile_phone.auth_code.to_s == params[:verification_code].to_s
      @mobile_phone.verified!
      flash[:notice] = 'Thanks! Your phone number is now verified.'
    else
      flash[:warning] = 'Invalid verification code.'
    end
    redirect_to user_mobile_phone_path(current_user, @mobile_phone)
  end

  # POST /mobile_phones/1/reset
  def reset
    if @mobile_phone.reset!
      flash[:notice] = 'We\'re resetting your authorization code.'
    else
      flash[:warning] = 'We could not reset your authorization code.'
    end
    redirect_to user_mobile_phone_path(current_user, @mobile_phone)
  end

  private

  def mobile_phone_params
    params.require(:mobile_phone).permit(:number).merge(user: current_user)
  end

  def set_mobile_phone
    @mobile_phone = MobilePhone.find(params[:id])
  end
end

app/views/mobile_phones/_form.html.haml
- if @mobile_phone.errors.any?
  #error_explanation.alert.alert-danger
    %ul.list-unstyled
      - @mobile_phone.errors.full_messages.each do |msg|
        %li= msg

.row
  = form_for([current_user, @mobile_phone], html: {role: 'form', class: 'col s12'}) do |f|
    .row
      .input-field.col.s12.m4
        = f.telephone_field :number, class: 'validate'
        = f.label :number, 'Mobile Phone Number'
    .row
      = f.submit 'Save', class: 'btn light-blue darken-3'
      or
      = link_to 'Cancel', :back

app/views/mobile_phones/edit.html.haml
= render 'form'

app/views/mobile_phones/new.html.haml
= render 'form'

app/views/mobile_phones/show.html.haml
- if @mobile_phone.unverified?
  - if @mobile_phone.errors.any?
    #error_explanation.alert-box.warning{data: alert}
      %ul.list-unstyled
        - @mobile_phone.errors.full_messages.each do |msg|
          %li= msg
      %a{href: "#", class: "close"} &times;

  = form_tag(verify_user_mobile_phone_path(current_user, @mobile_phone), class: 'form-inline', role: 'form') do
    .form-group
      = label_tag :verification_code, 'Verification Code', class: 'sr-only'
      = text_field_tag :verification_code, nil, class: 'form-control', maxlength: 5, placeholder: 'Code'
    %p.help-block
      Please use the passcode sent previously via SMS to verify
      your mobile phone number.
    .form-group
      = submit_tag 'Verify', class: 'btn btn-primary'
- else
  %p
    = @mobile_phone.number
    is verified.

- if @mobile_phone.unverified?
  %section
    = link_to 'Resend code', reset_user_mobile_phone_path(current_user, @mobile_phone), class: 'btn btn-default'