config/routes.rb
Rails.application.routes.draw do
  resources :user_sessions
  get 'login' => 'user_sessions#new', as: :login
  get 'logout' => 'user_sessions#destroy', as: :logout

  post 'sms/receive', to: 'sms#receive'
  get 'help', to: 'page#help', as: :help

  resources :users do
    resources :questions do
      resources :answers, except: [:new, :edit, :update, :create]
    end
    resources :mobile_phones, except: [:index] do
      member do
        post :verify
        get  :reset
      end
    end
  end

  root to: 'dashboard#index', constraints: RouteConstraints::UserRequiredConstraint.new,
       as: :dashboard
  root to: 'page#welcome', constraints: RouteConstraints::NoUserRequiredConstraint.new,
       as: :landing
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title Inquisitor
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  %body
    .row
      .col.s12.m4.l2.grey.lighten-2.z-depth-3
        .side-nav
          %h5.text-align.center
            = link_to "INQUISITOR", dashboard_path
          %ul
            %li
              = link_to 'Questions'
              = link_to "(+ add new)", new_user_question_path(current_user)
              %ul.nested
                - current_user.questions.each do |question|
                  %li= link_to question.body, user_question_path(current_user, question)
          %ul
          - if current_user.mobile_phone
            %li
              = link_to 'Update Mobile Phone',
                edit_user_mobile_phone_path(current_user, current_user.mobile_phone)
          - else
            %li
              = link_to 'Add Mobile Phone', new_user_mobile_phone_path(current_user)
          %li Download Data
          .user-nav
            %ul.text-align.center
              %li
                = link_to edit_user_path(current_user.id) do
                  = image_tag current_user.gravatar_url, size: '30', class: 'gravatar'
                  = current_user.short_name
            %hr
            %p
              = link_to "Logout", logout_path

      .col.s12.m8.l10
        = yield
    = javascript_include_tag 'application'

app/views/layouts/landing.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"}
    %title Inquisitor
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  %body
    %nav.white{:role => "navigation"}
      .nav-wrapper.container
        = link_to 'INQUISITOR', landing_path, class: 'logo-container brand-logo'
        %ul.right
          %li= link_to "Register", new_user_path
          %li= link_to "Login", login_path
        %ul#nav-mobile.side-nav
          %li= link_to "Register", new_user_path
          %li= link_to "Login", login_path
        %a.button-collapse{"data-activates" => "nav-mobile", :href => "#"}
          %i.mdi-navigation-menu
    = yield
    %footer.page-footer.teal
      .container
        .row
          .col.l6.s12
            %h5.white-text Company Bio
            %p.grey-text.text-lighten-4 We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.
          .col.l3.s12
            %h5.white-text Settings
            %ul
              %li
                %a.white-text{:href => "#!"} Link 1
              %li
                %a.white-text{:href => "#!"} Link 2
              %li
                %a.white-text{:href => "#!"} Link 3
              %li
                %a.white-text{:href => "#!"} Link 4
          .col.l3.s12
            %h5.white-text Connect
            %ul
              %li
                %a.white-text{:href => "#!"} Link 1
              %li
                %a.white-text{:href => "#!"} Link 2
              %li
                %a.white-text{:href => "#!"} Link 3
              %li
                %a.white-text{:href => "#!"} Link 4
      .footer-copyright
        .container
          Made by
          %a.brown-text.text-lighten-3{:href => "http://materializecss.com"} Materialize
    = javascript_include_tag 'application'